export const VendorFormField = {
  profile: [
    {
      tabName: "Basic Detail",
      isedit: false,
      formFields: [
        {
          name: "vendorId",
          label: "ID",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "name",
          label: "Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Primary Address",
      isedit: true,
      isParent: "primery_Address",
      formFields: [
        {
          name: "address",
          label: "Address",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "50%",
        },
        {
          name: "suite",
          label: "Suite",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "city",
          label: "City",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "state",
          label: "State",
          require: true,
          isErrorMsg: false,
          type: "select",
          width: "20%",
        },
        {
          name: "pincode",
          label: "Zip",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
          maxLength:5
        },
      ],
    },
    {
      tabName: "Billing Address",
      isedit: true,
      isParent: "secondary_Address",
      formFields: [
        {
          name: "address",
          label: "Address",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "50%",
        },
        {
          name: "suite",
          label: "Suite",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "city",
          label: "City",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "state",
          label: "State",
          require: true,
          isErrorMsg: false,
          type: "select",
          width: "20%",
        },
        {
          name: "pincode",
          label: "Zip",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
          maxLength:5
        },
      ],
    },
    {
      tabName: "Primary Contact",
      isedit: true,
      isParent: "primery_Contact",
      formFields: [
        {
          name: "firstName",
          label: "First Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "middleName",
          label: "Middle Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "lastName",
          label: "Last Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "phone",
          label: "Phone",
          require: true,
          isErrorMsg: false,
          type: "phone",
          width: "20%",
        },
        {
          name: "ext",
          label: "Ext",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "email",
          label: "Email",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "cellPhone",
          label: "Cell Phone",
          require: true,
          isErrorMsg: false,
          type: "phone",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Additional Contact",
      isedit: true,
      isParent: "secondary_contact",
      formFields: [
        {
          name: "firstName",
          label: "First Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "middleName",
          label: "Middle Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "lastName",
          label: "Last Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "phone",
          label: "Phone",
          require: false,
          isErrorMsg: false,
          type: "phone",
          width: "20%",
        },
        {
          name: "ext",
          label: "Ext",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "email",
          label: "Email",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "cellPhone",
          label: "Cell Phone",
          require: false,
          isErrorMsg: false,
          type: "phone",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Accounting Information",
      isedit: true,
      isParent: "accountinfo",
      formFields: [
        {
          name: "billing_Code",
          label: "Billing Code",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "billing_Name",
          label: "Billing Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "tax_Id",
          label: "Tax Id",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "custom_Field1",
          label: "Custom Field1",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "custom_Field2",
          label: "Custom Field2",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "profile_Note",
          label: "Profile Note",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "40%",
        },
      ],
    },
  ],
  communication: {
    tabName: "Communication",
    isParent: "communication",
    formFields: [
      {
        name: "type",
        label: "Type",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "method",
        label: "Method",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "detail",
        label: "Detail",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "product_id",
        label: "Product",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
    ],
  },
  additional: {
    tabName: "Additional",
    formFields: [
      {
        Checkname: "new_Assignment",
        Checkedlabel: "New Assignment",
        Textlabel: "Assignment Note",
        Textname: "assignmentNote",
      },
      {
        Checkname: "qcRejection",
        Checkedlabel: "QC Rejection",
        Textlabel: "QC Recjection Note",
        Textname: "qcRejectionNotes",
      },
      {
        Checkname: "dailyReminder",
        Checkedlabel: "Daily Reminder",
        Textlabel: "Daily Reminder Note",
        Textname: "dailyReminderNotes",
      },
      {
        Checkname: "profileReminder",
        Checkedlabel: "Profile Reminder",
        Textlabel: "Profile Reminder Note",
        Textname: "profileReminderNotes",
      },
    ],
  },
  licence: {
    tabName: "Licence",
    formFields: [
      {
        name: "firstName",
        label: "First Name",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "lastName",
        label: "Last Name",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "state",
        label: "State",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "licenceNo",
        label: "Licence No.",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "licenceType",
        label: "License Type",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "status",
        label: "Status",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "address",
        label: "Address",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "issueDate",
        label: "Issue Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "expiry_Date",
        label: "Expiry Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "disciplinaryAction",
        label: "Disciplinary/ Other Actions",
        require: false,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "note",
        label: "Note",
        require: false,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
    ],
  },
  fileupload: {
    tabName: "File Upload",
    formFields: [
      {
        name: "type",
        label: "Type",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "issueDate",
        label: "Issue Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "expiryDate",
        label: "Expiry Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "remarks",
        label: "Remarks",
        require: false,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
    ],
  },
  userregistration: {
    tabName: "User Registration",
    isParent: "userregistration",
    formFields: [
      {
        name: "firstName",
        label: "First Name",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "lastName",
        label: "Last Name",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "emailId",
        label: "Email",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "logId",
        label: "Log ID",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "password",
        label: "Password",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "cPassword",
        label: "Confirm Passwordd",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "allowTextMsg",
        label: "Allow Text",
        require: true,
        isErrorMsg: false,
        type: "check",
        width: "30%",
      },
    ],
  },
};
export const intiatalVendor = {
  id: 0,
  vendorId: "",
  name: "",
  primery_Address: {
    address: "",
    city: "",
    suite: "",
    state: "",
    pincode: "",
  },
  secondary_Address: {
    address: "",
    city: "",
    suite: "",
    state: "",
    pincode: "",
  },
  primery_Contact: {
    firstName: "",
    middleName: "",
    lastName: "",
    phone: "",
    email: "",
    ext: "",
    cellPhone: "",
  },
  secondary_contact: {
    firstName: "",
    middleName: "",
    lastName: "",
    phone: "",
    email: "",
    ext: "",
    cellPhone: "",
  },
  assignmentNote: "",
  new_Assignment: true,
  qcRejection: true,
  qcRejectionNotes: "",
  dailyReminder: true,
  dailyReminderNotes: "",
  profileReminder: true,
  profileReminderNotes: "",

  licences: [
    {
      firstName: "",
      lastName: "",
      licenceNo: "",
      licenceType: "",
      status: "",
      address: "",
      expiry_Date: "",
      issueDate: "",
      disciplinaryAction: "",
      note: "",
      state: "",
    },
  ],
  communication: [
    {
      type: "",
      detail: "",
      product_id: 0,
      method: "",
    },
  ],
  userregistration: {
    firstName: "",
    lastName: "",
    emailId: "",
    logId: "",
    password: "",
    allowTextMsg: true,
  },
  product: [
    {
      id: "",
      name: "string",
      price1: 0,
      price2: 0,
      price3: 0,
      productId: 0,
      selected: false,
      productPriceList: [],
    },
  ],
  productFiles: [
    {
      fileName: "",
      location: "",
      size: 0,
      file: "",
      type: "",
      remarks: "",
      issueDate: "",
      expiryDate: "",
      fileid: 0,
    },
  ],
  accountinfo: {
    billing_Code: "",
    billing_Name: "",
    tax_Id: "",
    custom_Field1: "",
    custom_Field2: "",
    profile_Note: "",
  },
};

export const intiatalCustomer = {
  customerId: "",
  name: "",
  parent: "",
  client_type: "",
  timezone: "",
  primery_Address: {
    address: "",
    city: "",
    suite: "",
    state: "",
    pincode: "",
  },
  secondary_Address: {
    address: "",
    city: "",
    suite: "",
    state: "",
    pincode: "",
  },
  primery_Contact: {
    firstName: "",
    middleName: "",
    lastName: "",
    phone: "",
    email: "",
    ext: "",
    cellPhone: "",
  },
  secondary_contact: {
    firstName: "",
    middleName: "",
    lastName: "",
    phone: "",
    email: "",
    ext: "",
    cellPhone: "",
  },
  order_Confirmation: false,
  assignment: false,
  inspection: false,
  in_QC_Review: false,
  order_ConfirmationNotes: "",
  assignmentNotes: "",
  inspectionNotes: "",
  in_QC_ReviewNotes: "",
  uploadedfile: "string",
  communication: [
    {
      vendorId: 0,
      type: "",
      detail: "",
      product_id: 0,
      customerId: 0,
      method: "",
    },
  ],
  product: [
    {
      id: 0,
      name: "string",
      price1: 0,
      price2: 0,
      price3: 0,
      productId: 0,
      selected: true,
      subCategory: [null],
    },
  ],
  additionalDetail: [""],
  customer_Integration_details: {
    detail: "",
    port: "",
    login: "",
    password: "",
    customerId: 0,
  },
  registerId: [],
  accountinfo: {
    billing_Code: "",
    billing_Name: "",
    tax_Id: "",
    custom_Field1: "",
    custom_Field2: "",
    profile_Note: "",
  },
  productFiles: [
    {
      fileName: "",
      location: "",
      size: 0,
      file: "",
      type: "",
      remarks: "",
      issueDate: "",
      expiryDate: "",
      fileid: 0,
    },
  ],
};
export const CustomerFormField = {
  profile: [
    {
      tabName: "Basic Detail",
      isedit: false,
      formFields: [
        {
          name: "customerId",
          label: "ID",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "name",
          label: "Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "parent",
          label: "Parent",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "client_type",
          label: "Type",
          require: true,
          isErrorMsg: false,
          type: "select",
          width: "20%",
        },
        {
          name: "timezone",
          label: "Time zone",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Primary Address",
      isedit: true,
      isParent: "primery_Address",
      formFields: [
        {
          name: "address",
          label: "Address",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "50%",
        },
        {
          name: "suite",
          label: "Suite",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "city",
          label: "City",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "state",
          label: "State",
          require: true,
          isErrorMsg: false,
          type: "select",
          width: "20%",
        },
        {
          name: "pincode",
          label: "Zip",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
          maxLength:"5"
        },
      ],
    },
    {
      tabName: "Billing Address",
      isedit: true,
      isParent: "secondary_Address",
      formFields: [
        {
          name: "address",
          label: "Address",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "50%",
        },
        {
          name: "suite",
          label: "Suite",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "city",
          label: "City",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "state",
          label: "State",
          require: true,
          isErrorMsg: false,
          type: "select",
          width: "20%",
        },
        {
          name: "pincode",
          label: "Zip",
          require: true,
          isErrorMsg: false,
          type: "text",
          maxLength:"5",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Primary Contact",
      isedit: true,
      isParent: "primery_Contact",
      formFields: [
        {
          name: "firstName",
          label: "First Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "middleName",
          label: "Middle Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "lastName",
          label: "Last Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "phone",
          label: "Phone",
          require: true,
          isErrorMsg: false,
          type: "phone",
          width: "20%",
        },
        {
          name: "ext",
          label: "Ext",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "email",
          label: "Email",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "cellPhone",
          label: "Cell Phone",
          require: true,
          isErrorMsg: false,
          type: "phone",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Additional Contact",
      isedit: true,
      isParent: "secondary_contact",
      formFields: [
        {
          name: "firstName",
          label: "First Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "middleName",
          label: "Middle Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "lastName",
          label: "Last Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "phone",
          label: "Phone",
          require: false,
          isErrorMsg: false,
          type: "phone",
          width: "20%",
        },
        {
          name: "ext",
          label: "Ext",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "email",
          label: "Email",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "cellPhone",
          label: "Cell Phone",
          require: false,
          isErrorMsg: false,
          type: "phone",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Accounting Information",
      isedit: true,
      isParent: "accountinfo",
      formFields: [
        {
          name: "billing_Code",
          label: "Billing Code",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "billing_Name",
          label: "Billing Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "tax_Id",
          label: "Tax Id",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "custom_Field1",
          label: "Custom Field1",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "custom_Field2",
          label: "Custom Field2",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "profile_Note",
          label: "Profile Note",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "40%",
        },
      ],
    },
  ],
  communication: {
    tabName: "Communication",
    isParent: "communication",
    formFields: [
      {
        name: "type",
        label: "Type",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "method",
        label: "Method",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "detail",
        label: "Detail",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "product_id",
        label: "Product",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
    ],
  },
  additional: {
    tabName: "Additional",
    formFields: [
      {
        Checkname: "order_Confirmation",
        Checkedlabel: "Order Confirmation",
        Textlabel: "Order Confirmation Note",
        Textname: "order_ConfirmationNotes",
      },
      {
        Checkname: "assignment",
        Checkedlabel: "Assignment",
        Textlabel: "Assignment Note",
        Textname: "assignmentNotes",
      },
      {
        Checkname: "inspection",
        Checkedlabel: "Inspection",
        Textlabel: "Inspection Note",
        Textname: "inspectionNotes",
      },
      {
        Checkname: "in_QC_Review",
        Checkedlabel: "In QC Review",
        Textlabel: "In QC Note",
        Textname: "in_QC_ReviewNotes",
      },
    ],
  },
  customer_Integration_details: {
    tabName: "Customer Integration Details",
    isParent: "customer_Integration_details",
    formFields: [
      {
        name: "detail",
        label: "Detail",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "port",
        label: "Port",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "login",
        label: "Login",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "password",
        label: "Password",
        require: true,
        isErrorMsg: false,
        type: "password",
        width: "20%",
      },
     
     
     
    ],
  },
  fileupload: {
    tabName: "File Upload",
    formFields: [
      {
        name: "type",
        label: "Type",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "issueDate",
        label: "Issue Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "expiryDate",
        label: "Expiry Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "remarks",
        label: "Remarks",
        require: false,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
    ],
  },
  userregistration: {
    tabName: "User Registration",
    isParent: "userregistration",
    formFields: [
      {
        name: "firstName",
        label: "First Name",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "lastName",
        label: "Last Name",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "emailId",
        label: "Email",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "logId",
        label: "Log ID",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "password",
        label: "Password",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "cPassword",
        label: "Confirm Passwordd",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "allowTextMsg",
        label: "Allow Text",
        require: true,
        isErrorMsg: false,
        type: "check",
        width: "15%",
      },
    ],
  },
};
