export const VendorFormField = {
  profile: [
    {
      tabName: "Basic Detail",
      formFields: [
        {
          name: "vendorId",
          label: "ID",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "name",
          label: "Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Primary Address",
      isParent: "primery_Address",
      formFields: [
        {
          name: "address",
          label: "Address",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "50%",
        },
        {
          name: "suite",
          label: "Suite",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "city",
          label: "City",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "state",
          label: "State",
          require: true,
          isErrorMsg: false,
          type: "select",
          width: "20%",
        },
        {
          name: "pincode",
          label: "Zip",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Billing Address",
      isParent: "secondary_Address",
      formFields: [
        {
          name: "address",
          label: "Address",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "50%",
        },
        {
          name: "suite",
          label: "Suite",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "city",
          label: "City",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "25%",
        },
        {
          name: "state",
          label: "State",
          require: true,
          isErrorMsg: false,
          type: "select",
          width: "20%",
        },
        {
          name: "pincode",
          label: "Zip",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Primary Contact",
      isParent: "primery_Contact",
      formFields: [
        {
          name: "firstname",
          label: "First Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "middleName",
          label: "Middle Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "lastname",
          label: "Last Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "phone",
          label: "Phone",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "ext",
          label: "Ext",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "email",
          label: "Email",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "cellphone",
          label: "Cell Phone",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Additional Contact",
      isParent: "secondary_contact",
      formFields: [
        {
          name: "firstname",
          label: "First Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "middleName",
          label: "Middle Name",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "lastname",
          label: "Last Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "phone",
          label: "Phone",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "ext",
          label: "Ext",
          require: false,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "email",
          label: "Email",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "cellphone",
          label: "Cell Phone",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
      ],
    },
    {
      tabName: "Accounting Information",
      isParent: "accountinfo",
      formFields: [
        {
          name: "billing_Code",
          label: "Billing Code",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "billing_Name",
          label: "Billing Name",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "tax_Id",
          label: "Tax Id",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "custom_Field1",
          label: "Custom Field1",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "custom_Field2",
          label: "Custom Field2",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "20%",
        },
        {
          name: "profile_Note",
          label: "Profile Note",
          require: true,
          isErrorMsg: false,
          type: "text",
          width: "40%",
        },
      ],
    },
  ],
  communication: {
    tabName: "Communication",
    formFields: [
      {
        name: "type",
        label: "Type",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "method",
        label: "Method",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "detail",
        label: "Detail",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "product_id",
        label: "Product",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
    ],
  },
  additional: {
    tabName: "Additional",
    formFields: [
      {
        Checkname: "new_Assignment",
        Checkedlabel: "New Assignment",
        Textlabel: "Assignment Note",
        Textname: "assignmentNote",
      },
      {
        Checkname: "qcRejection",
        Checkedlabel: "QC Rejection",
        Textlabel: "QC Recjection Note",
        Textname: "qcRejectionNotes",
      },
      {
        Checkname: "dailyReminder",
        Checkedlabel: "Daily Reminder",
        Textlabel: "Daily Reminder Note",
        Textname: "dailyReminderNotes",
      },
      {
        Checkname: "profileReminder",
        Checkedlabel: "Profile Reminder",
        Textlabel: "Profile Reminder Note",
        Textname: "profileReminderNotes",
      },
    ],
  },
  licence: {
    tabName: "Licence",
    formFields: [
      {
        name: "firstName",
        label: "First Name",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "lastName",
        label: "Last Name",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "state",
        label: "State",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "licenceNo",
        label: "Licence No.",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "licenceType",
        label: "License Type",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "status",
        label: "Status",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "address",
        label: "Address",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "issueDate",
        label: "Issue Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "expiry_Date",
        label: "Expiry Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "disciplinaryAction",
        label: "Disciplinary/ Other Actions",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
      {
        name: "note",
        label: "Note",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
    ],

  },
  fileupload: {
    tabName: "File Upload",
    formFields: [
      {
        name: "type",
        label: "Type",
        require: true,
        isErrorMsg: false,
        type: "select",
        width: "20%",
      },
      {
        name: "issueDate",
        label: "Issue Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "expiryDate",
        label: "Expiry Date",
        require: true,
        isErrorMsg: false,
        type: "date",
        width: "20%",
      },
      {
        name: "remarks",
        label: "Remarks",
        require: true,
        isErrorMsg: false,
        type: "text",
        width: "20%",
      },
    ],
  },
};
export const intiatalVendor = {
  id: 0,
  vendorId: "",
  name: "",
  primery_Address: {
    address: "",
    city: "",
    suite: "",
    state: "",
    pincode: "",
  },
  secondary_Address: {
    address: "",
    city: "",
    suite: "",
    state: "",
    pincode: "",
  },
  primery_Contact: {
    firstName: "",
    middleName: "",
    lastName: "",
    phone: "",
    email: "",
    ext: "",
    cellPhone: "",
  },
  secondary_contact: {
    firstName: "",
    middleName: "",
    lastName: "",
    phone: "",
    email: "",
    ext: "",
    cellPhone: "",
  },
  assignmentNote: "",
  new_Assignment: true,
  qcRejection: true,
  qcRejectionNotes: "",
  dailyReminder: true,
  dailyReminderNotes: "",
  profileReminder: true,
  profileReminderNotes: "",

  licences: [
    {
      firstName: "",
      lastName: "",
      licenceNo: "",
      licenceType: "",
      status: "",
      address: "",
      expiry_Date: "",
      issueDate: "",
      disciplinaryAction: "",
      note: "",
      state: "",
    },
  ],
  communication: [
    {
      type: "",
      detail: "",
      product_id: 0,
      method: "",
    },
  ],
  userregistration: {
    firstName: "",
    lastName: "",
    emailId: "",
    logId: "",
    password: "",
    allowTextMsg: true,
  },
  product: [
    {
      id: "",
      name: "string",
      price1: 0,
      price2: 0,
      price3: 0,
      productId: 0,
      selected: false,
      productPriceList: [],
    },
  ],
  productFiles: [
    {
      fileName: "",
      location: "",
      size: 0,
      file: "",
      type: "",
      remarks: "",
      issueDate: "",
      expiryDate: "",
      fileid: 0,
    },
  ],
  accountinfo: {
    billing_Code: "",
    billing_Name: "",
    tax_Id: "",
    custom_Field1: "",
    custom_Field2: "",
    profile_Note: "",
  },
};
