import {
  LicenceTypeSchema,
  CommunicationTypeSchema,
  StateSchema,
  RoleSchema,
  AccessRoleSchema,
} from "../../schemas";
export const HeadingName = [
  {
    label: "Licence Type",
    id: "licencetype",
    formfield: [
      {
        label: "Licence Type",
        name: "name",
        required: true,
        isErrorMsg: false,
        type:'text'
      },
    ],
    initialValue: { name: "" },
    schema: LicenceTypeSchema,
    TableColumn: [
      { id: "id", label: "S. No.", minWidth: 100, flex: 1, renderCell: false },
      { id: "name", label: "Name", minWidth: 100, flex: 1, renderCell: false },
      {
        id: "createdDate",
        label: "Created Date",
        minWidth: 100,
        flex: 1,
        renderCell: false,
      },
      {
        id: "updateDate",
        label: "Updated Date",
        minWidth: 100,
        flex: 1,
        renderCell: false,
      },
      {
        id: "Action",
        label: "Action",
        renderCell: true,
        flex: 1,
        minWidth: 100,
      },
    ],
  },
  {
    label: "Communication Type",
    id: "communicationtype",
    formfield: [
      {
        label: "Code",
        name: "uniquename",
        required: true,
        isErrorMsg: false,
        type:'text'
      },
      {
        label: "Communication Type",
        name: "name",
        required: true,
        isErrorMsg: false,
        type:'text'
      },
    ],
    initialValue: { name: "", uniquename: "" },
    schema: CommunicationTypeSchema,
    TableColumn: [
      { id: "id", label: "S. No.", minWidth: 100, flex: 1, renderCell: false },
      {
        id: "uniquename",
        label: "Code",
        minWidth: 100,
        flex: 1,
        renderCell: false,
      },
      { id: "name", label: "Name", minWidth: 100, flex: 1, renderCell: false },
      {
        id: "createdDate",
        label: "Created Date",
        minWidth: 100,
        flex: 1,
        renderCell: false,
      },
      {
        id: "updateDate",
        label: "Updated Date",
        minWidth: 100,
        flex: 1,
        renderCell: false,
      },
      {
        id: "Action",
        label: "Action",
        renderCell: true,
        flex: 1,
        minWidth: 100,
      },
    ],
  },
  {
    label: "State",
    id: "state",
    formfield: [
      {
        label: "State Name",
        name: "name",
        required: true,
        isErrorMsg: false,
        type:'text'
      },
    ],
    initialValue: { name: "" },
    schema: StateSchema,
    TableColumn: [
      { id: "id", label: "S. No.", minWidth: 100, flex: 1, renderCell: false },
      { id: "name", label: "Name", minWidth: 100, flex: 1, renderCell: false },
      {
        id: "createdDate",
        label: "Created Date",
        minWidth: 100,
        flex: 1,
        renderCell: false,
      },
      {
        id: "updateDate",
        label: "Updated Date",
        minWidth: 100,
        flex: 1,
        renderCell: false,
      },
     
    ],
  },
  {
    label: "Role Master",
    id: "role",
    formfield: [
      {
        label: "Role Name",
        name: "name",
        required: true,
        isErrorMsg: false,
        type:'text'
      },
      {
        label: "Description",
        name: "description",
        required: true,
        isErrorMsg: false,
        type:'text'
      },
    ],
    initialValue: { name: "", description: "" },
    schema: RoleSchema,
    TableColumn: [
      { id: "id", label: "S No.", flex: 1, renderCell: false },
      { id: "name", label: "Name", flex: 1, renderCell: false },
      { id: "description", label: "Description", flex: 1, renderCell: false },
      {
        id: "Action",
        label: "Action",
        renderCell: true,
        flex: 1,
      },
    ],
  },
  {
    label: "Access Control Master",
    id: "accessrole",
    formfield: [
      {
        label: "Access Control Name",
        name: "subrole",
        required: true,
        isErrorMsg: false,
        type:'text'
      },
    ],
    initialValue: { subrole: "" },
    schema: AccessRoleSchema,
    TableColumn: [
      { id: "id", label: "S No.", flex: 1, renderCell: false },
      { id: "subrole", label: "Access Name", flex: 1, renderCell: false },
      {
        id: "Action",
        label: "Action",
        renderCell: true,
        flex: 1,
      },
    ],
  },
  {
    label: "Add Users",
    id: "user",
    formfield: [
      {
        label: "User Type",
        name: "userType",
        required: true,
        isErrorMsg: false,
        type: "select",
      },
      {
        label: "Manager",
        name: "manager",
        required: true,
        isErrorMsg: false,
        type: "select",
      },
      {
        label: "Department",
        name: "department",
        required: true,
        isErrorMsg: false,
        type: "select",
      },
      {
        label: "First Name",
        name: "firstName",
        required: true,
        isErrorMsg: false,
        type: "text",
        width:'50%'
      },
      {
        label: "Last Name",
        name: "lastName",
        required: true,
        isErrorMsg: false,
        type: "text",
        width:'50%'
      },
      {
        label: "Email Id",
        name: "emailId",
        required: true,
        isErrorMsg: false,
        type: "text",
      },
      {
        label: "Login Id",
        name: "logId",
        required: true,
        isErrorMsg: false,
        type: "text",
      },
      {
        label: "Password",
        name: "password",
        required: true,
        isErrorMsg: false,
        type: "text",
      },
      {
        label: "Confirm Password",
        name: "Cpassword",
        required: true,
        isErrorMsg: false,
        type: "text",
      },
      {
        label: "Out Email",
        name: "outEmail",
        required: false,
        isErrorMsg: false,
        type: "text",
      },
      {
        label: "Cell Phone",
        name: "cellPhone",
        required: false,
        isErrorMsg: false,
        type: "text",
      },
      {
        label: "Hours",
        name: "Hour",
        required: false,
        isErrorMsg: false,
        type: "select",
        width:'30%',
        parentLabel:'Work Start Time',
        groupBy:'wst'
      },
      {
        label: "Minute",
        name: "Minute",
        required: false,
        isErrorMsg: false,
        type: "select",
        width:'40%',
        groupBy:'wst'
      },
      {
        label: "AM/PM",
        name: "type",
        required: false,
        isErrorMsg: false,
        type: "select",
        width:'30%',
        groupBy:'wst'
      },

      {
        label: "Hours",
        name: "Hour",
        required: false,
        isErrorMsg: false,
        type: "select",
        width:'30%',
        parentLabel:'Work End Time',
        groupBy:'wet'
      },
      {
        label: "Minute",
        name: "Minute",
        required: false,
        isErrorMsg: false,
        type: "select",
        width:'40%',
        groupBy:'wet'
      },
      {
        label: "AM/PM",
        name: "type",
        required: false,
        isErrorMsg: false,
        type: "select",
        width:'30%',
        groupBy:'wet'
      },
      {
        label: "Email Signature",
        name: "emailSignature",
        required: false,
        isErrorMsg: false,
        type: "text",
      },
    ],
    initialValue: {
      userType: "",
      firstName: "",
      lastName: "",
      emailId: "",
      logId: "",
      password: "",
      outEmail: "",
      cellPhone: "",
      allowTextMsg: false,
      manager: "",
      department: "",
      workStartH: 0,
      workStartM: 0,
      workEndH: 0,
      workEndM: 0,
      emailSignature: "",
    },
    schema: "",
    TableColumn: [
      { id: "id", label: "S No.", minWidth: 50, renderCell: false, flex: 1 },
      { id: "name", label: "Name", minWidth: 150, renderCell: false, flex: 1 },
      {
        id: "username",
        label: "User Name",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "userType",
        label: "User Type",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "emailId",
        label: "Email Id",
        minWidth: 250,
        renderCell: false,
        flex: 1,
      },
      {
        id: "outEmail",
        label: "Out Email",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "cellPhone",
        label: "Cell Phone",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "allowTextMsg",
        label: "Allow Text Msg",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "manager",
        label: "Manager",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "department",
        label: "Department",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "workStart",
        label: "Work Start",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "workEnd",
        label: "Work End",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "emailSignature",
        label: "Email Signature",
        minWidth: 150,
        renderCell: false,
        flex: 1,
      },
      {
        id: "roles",
        label: "User Role",
        minWidth: 250,
        renderCell: false,
        flex: 1,
      },
    ],
  },
];
