/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ec22eb0d-b872-4ab8-a452-2b6c23a70ed4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SGoFq76ax",
    "aws_user_pools_web_client_id": "1uomjp5vb6fk59vnavr67j6957",
    "oauth": {
        "domain": "mrtggrp.auth.us-east-2.amazoncognito.com",
        "scope": [
            "aws.cognito.signin.user.admin",
            "http://localhost:3000/authapp.all",
            "openid",
            "phone",
            "profile"
        ],
        "redirectSignIn": "http://localhost:3000/callback",
        "redirectSignOut": "http://localhost:3000/presentation",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
